#!/usr/bin/php
<?php
require "../vendor/autoload.php";

echo " -----------------------------------------------\n";
echo "|     Welcome to the CRUD application           |\n";


$processend = false;
$round =0;
while(!$processend){
    echo " -----------------------------------------------\n";
    echo "|Execute command (create, update, delete, read) |\n";
    echo " -----------------------------------------------\n";
    $command = readline();
    echo "\n";
    switch($command){
        case "read":
            \Http\Controllers\ShellController::index();
        break;
        case "delete":
            \Http\Controllers\ShellController::delete();
        break;
        case "create":
            \Http\Controllers\ShellController::create();
        break;
        case "update":
            \Http\Controllers\ShellController::update();
        break;
        case "getout"or "exit":
            $processend = true;
        break;
    }
}